glibc: Rework locale-gen and improve stripping.
I didn't think to include the STRIP_* variables defined in
/etc/makepkg.conf which resulted in many missed opportunities and thus a
larger resulting package.  Correctly stripping shared, static and
binaries saved a futher 8M.

Locale-gen was also changed to be a bit simpler.  Error out if the
locales file is empty now.  I had intended on allowing users to add
locales via locale-gen but decided against it as it merely replicates
redirection with added complexity which don't appear to be justified.

diff --git a/glibc-git/locale-gen b/glibc-git/locale-gen
--- a/glibc-git/locale-gen
+++ b/glibc-git/locale-gen
@@ -1,20 +1,14 @@
-#!/bin/bash
+#!/bin/sh
 
-in_array() {
-    local i
-    for i in "${@:2}"; do
-        [[ $1 = "$i" ]] && return 0
-    done
-    return 1
-}
-
-valid_locales=(/usr/share/i18n/locales/*)
+if [[ ! -s /etc/locales ]]; then
+    printf '/etc/locales: Empty or missing.\n'
+    exit 1
+fi
 
 while read -r locale; do
-    if in_array "$locale" "${valid_locales[@]##*/}"; then
-        printf 'Generating locale %s...\n' "$locale".UTF-8
-        localedef -i "$locale" -f UTF-8 -c "$locale".UTF-8
-    else
+    printf 'Generating locale %s...\n' "$locale".UTF-8
+
+    if ! localedef -i "$locale" -f UTF-8 -c "$locale".UTF-8; then
         printf '%s: Invalid locale.\n' "$locale"
     fi
 done < /etc/locales
